sequenceDiagram

participant Server; participant Client;

alt DH密钥交换
    Server-->>Client: Public Message [prime g,p]
    Client-->>Server: Private Message [g^Xc mod p]
    Server->>Server: Get shared key
    Server-->>Client: Private Message [g^Xs mod p]
    Client->>Client: Get shared key
end
alt AES CBC 加密传输 Server->Client
	Server->>Server: Get CBC key&iv
	Server-->>Client: 32bytes encrypted l
	Client->>Client: Get decypted l
	Server->>Client: l bytes encrypted message
	Client->>Client: Get decrypted message
end