# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /media/data/program/git/TlsUdpProtocol

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /media/data/program/git/TlsUdpProtocol

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /media/data/program/git/TlsUdpProtocol/CMakeFiles /media/data/program/git/TlsUdpProtocol/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /media/data/program/git/TlsUdpProtocol/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named appclient

# Build rule for target.
appclient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 appclient
.PHONY : appclient

# fast build rule for target.
appclient/fast:
	$(MAKE) -f CMakeFiles/appclient.dir/build.make CMakeFiles/appclient.dir/build
.PHONY : appclient/fast

#=============================================================================
# Target rules for targets named reliableserver

# Build rule for target.
reliableserver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 reliableserver
.PHONY : reliableserver

# fast build rule for target.
reliableserver/fast:
	$(MAKE) -f CMakeFiles/reliableserver.dir/build.make CMakeFiles/reliableserver.dir/build
.PHONY : reliableserver/fast

#=============================================================================
# Target rules for targets named udptelnet

# Build rule for target.
udptelnet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 udptelnet
.PHONY : udptelnet

# fast build rule for target.
udptelnet/fast:
	$(MAKE) -f CMakeFiles/udptelnet.dir/build.make CMakeFiles/udptelnet.dir/build
.PHONY : udptelnet/fast

#=============================================================================
# Target rules for targets named udpserver

# Build rule for target.
udpserver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 udpserver
.PHONY : udpserver

# fast build rule for target.
udpserver/fast:
	$(MAKE) -f CMakeFiles/udpserver.dir/build.make CMakeFiles/udpserver.dir/build
.PHONY : udpserver/fast

#=============================================================================
# Target rules for targets named reliabletelnet

# Build rule for target.
reliabletelnet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 reliabletelnet
.PHONY : reliabletelnet

# fast build rule for target.
reliabletelnet/fast:
	$(MAKE) -f CMakeFiles/reliabletelnet.dir/build.make CMakeFiles/reliabletelnet.dir/build
.PHONY : reliabletelnet/fast

#=============================================================================
# Target rules for targets named appserver

# Build rule for target.
appserver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 appserver
.PHONY : appserver

# fast build rule for target.
appserver/fast:
	$(MAKE) -f CMakeFiles/appserver.dir/build.make CMakeFiles/appserver.dir/build
.PHONY : appserver/fast

#=============================================================================
# Target rules for targets named secureserver

# Build rule for target.
secureserver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 secureserver
.PHONY : secureserver

# fast build rule for target.
secureserver/fast:
	$(MAKE) -f CMakeFiles/secureserver.dir/build.make CMakeFiles/secureserver.dir/build
.PHONY : secureserver/fast

#=============================================================================
# Target rules for targets named securetelnet

# Build rule for target.
securetelnet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 securetelnet
.PHONY : securetelnet

# fast build rule for target.
securetelnet/fast:
	$(MAKE) -f CMakeFiles/securetelnet.dir/build.make CMakeFiles/securetelnet.dir/build
.PHONY : securetelnet/fast

AppSocket.o: AppSocket.cpp.o

.PHONY : AppSocket.o

# target to build an object file
AppSocket.cpp.o:
	$(MAKE) -f CMakeFiles/appclient.dir/build.make CMakeFiles/appclient.dir/AppSocket.cpp.o
	$(MAKE) -f CMakeFiles/appserver.dir/build.make CMakeFiles/appserver.dir/AppSocket.cpp.o
.PHONY : AppSocket.cpp.o

AppSocket.i: AppSocket.cpp.i

.PHONY : AppSocket.i

# target to preprocess a source file
AppSocket.cpp.i:
	$(MAKE) -f CMakeFiles/appclient.dir/build.make CMakeFiles/appclient.dir/AppSocket.cpp.i
	$(MAKE) -f CMakeFiles/appserver.dir/build.make CMakeFiles/appserver.dir/AppSocket.cpp.i
.PHONY : AppSocket.cpp.i

AppSocket.s: AppSocket.cpp.s

.PHONY : AppSocket.s

# target to generate assembly for a file
AppSocket.cpp.s:
	$(MAKE) -f CMakeFiles/appclient.dir/build.make CMakeFiles/appclient.dir/AppSocket.cpp.s
	$(MAKE) -f CMakeFiles/appserver.dir/build.make CMakeFiles/appserver.dir/AppSocket.cpp.s
.PHONY : AppSocket.cpp.s

Client/AppClient.o: Client/AppClient.cpp.o

.PHONY : Client/AppClient.o

# target to build an object file
Client/AppClient.cpp.o:
	$(MAKE) -f CMakeFiles/appclient.dir/build.make CMakeFiles/appclient.dir/Client/AppClient.cpp.o
.PHONY : Client/AppClient.cpp.o

Client/AppClient.i: Client/AppClient.cpp.i

.PHONY : Client/AppClient.i

# target to preprocess a source file
Client/AppClient.cpp.i:
	$(MAKE) -f CMakeFiles/appclient.dir/build.make CMakeFiles/appclient.dir/Client/AppClient.cpp.i
.PHONY : Client/AppClient.cpp.i

Client/AppClient.s: Client/AppClient.cpp.s

.PHONY : Client/AppClient.s

# target to generate assembly for a file
Client/AppClient.cpp.s:
	$(MAKE) -f CMakeFiles/appclient.dir/build.make CMakeFiles/appclient.dir/Client/AppClient.cpp.s
.PHONY : Client/AppClient.cpp.s

ReliableSocket.o: ReliableSocket.cpp.o

.PHONY : ReliableSocket.o

# target to build an object file
ReliableSocket.cpp.o:
	$(MAKE) -f CMakeFiles/appclient.dir/build.make CMakeFiles/appclient.dir/ReliableSocket.cpp.o
	$(MAKE) -f CMakeFiles/reliableserver.dir/build.make CMakeFiles/reliableserver.dir/ReliableSocket.cpp.o
	$(MAKE) -f CMakeFiles/reliabletelnet.dir/build.make CMakeFiles/reliabletelnet.dir/ReliableSocket.cpp.o
	$(MAKE) -f CMakeFiles/appserver.dir/build.make CMakeFiles/appserver.dir/ReliableSocket.cpp.o
	$(MAKE) -f CMakeFiles/secureserver.dir/build.make CMakeFiles/secureserver.dir/ReliableSocket.cpp.o
	$(MAKE) -f CMakeFiles/securetelnet.dir/build.make CMakeFiles/securetelnet.dir/ReliableSocket.cpp.o
.PHONY : ReliableSocket.cpp.o

ReliableSocket.i: ReliableSocket.cpp.i

.PHONY : ReliableSocket.i

# target to preprocess a source file
ReliableSocket.cpp.i:
	$(MAKE) -f CMakeFiles/appclient.dir/build.make CMakeFiles/appclient.dir/ReliableSocket.cpp.i
	$(MAKE) -f CMakeFiles/reliableserver.dir/build.make CMakeFiles/reliableserver.dir/ReliableSocket.cpp.i
	$(MAKE) -f CMakeFiles/reliabletelnet.dir/build.make CMakeFiles/reliabletelnet.dir/ReliableSocket.cpp.i
	$(MAKE) -f CMakeFiles/appserver.dir/build.make CMakeFiles/appserver.dir/ReliableSocket.cpp.i
	$(MAKE) -f CMakeFiles/secureserver.dir/build.make CMakeFiles/secureserver.dir/ReliableSocket.cpp.i
	$(MAKE) -f CMakeFiles/securetelnet.dir/build.make CMakeFiles/securetelnet.dir/ReliableSocket.cpp.i
.PHONY : ReliableSocket.cpp.i

ReliableSocket.s: ReliableSocket.cpp.s

.PHONY : ReliableSocket.s

# target to generate assembly for a file
ReliableSocket.cpp.s:
	$(MAKE) -f CMakeFiles/appclient.dir/build.make CMakeFiles/appclient.dir/ReliableSocket.cpp.s
	$(MAKE) -f CMakeFiles/reliableserver.dir/build.make CMakeFiles/reliableserver.dir/ReliableSocket.cpp.s
	$(MAKE) -f CMakeFiles/reliabletelnet.dir/build.make CMakeFiles/reliabletelnet.dir/ReliableSocket.cpp.s
	$(MAKE) -f CMakeFiles/appserver.dir/build.make CMakeFiles/appserver.dir/ReliableSocket.cpp.s
	$(MAKE) -f CMakeFiles/secureserver.dir/build.make CMakeFiles/secureserver.dir/ReliableSocket.cpp.s
	$(MAKE) -f CMakeFiles/securetelnet.dir/build.make CMakeFiles/securetelnet.dir/ReliableSocket.cpp.s
.PHONY : ReliableSocket.cpp.s

SecureSocket.o: SecureSocket.cpp.o

.PHONY : SecureSocket.o

# target to build an object file
SecureSocket.cpp.o:
	$(MAKE) -f CMakeFiles/appclient.dir/build.make CMakeFiles/appclient.dir/SecureSocket.cpp.o
	$(MAKE) -f CMakeFiles/appserver.dir/build.make CMakeFiles/appserver.dir/SecureSocket.cpp.o
	$(MAKE) -f CMakeFiles/secureserver.dir/build.make CMakeFiles/secureserver.dir/SecureSocket.cpp.o
	$(MAKE) -f CMakeFiles/securetelnet.dir/build.make CMakeFiles/securetelnet.dir/SecureSocket.cpp.o
.PHONY : SecureSocket.cpp.o

SecureSocket.i: SecureSocket.cpp.i

.PHONY : SecureSocket.i

# target to preprocess a source file
SecureSocket.cpp.i:
	$(MAKE) -f CMakeFiles/appclient.dir/build.make CMakeFiles/appclient.dir/SecureSocket.cpp.i
	$(MAKE) -f CMakeFiles/appserver.dir/build.make CMakeFiles/appserver.dir/SecureSocket.cpp.i
	$(MAKE) -f CMakeFiles/secureserver.dir/build.make CMakeFiles/secureserver.dir/SecureSocket.cpp.i
	$(MAKE) -f CMakeFiles/securetelnet.dir/build.make CMakeFiles/securetelnet.dir/SecureSocket.cpp.i
.PHONY : SecureSocket.cpp.i

SecureSocket.s: SecureSocket.cpp.s

.PHONY : SecureSocket.s

# target to generate assembly for a file
SecureSocket.cpp.s:
	$(MAKE) -f CMakeFiles/appclient.dir/build.make CMakeFiles/appclient.dir/SecureSocket.cpp.s
	$(MAKE) -f CMakeFiles/appserver.dir/build.make CMakeFiles/appserver.dir/SecureSocket.cpp.s
	$(MAKE) -f CMakeFiles/secureserver.dir/build.make CMakeFiles/secureserver.dir/SecureSocket.cpp.s
	$(MAKE) -f CMakeFiles/securetelnet.dir/build.make CMakeFiles/securetelnet.dir/SecureSocket.cpp.s
.PHONY : SecureSocket.cpp.s

Server/AppServer.o: Server/AppServer.cpp.o

.PHONY : Server/AppServer.o

# target to build an object file
Server/AppServer.cpp.o:
	$(MAKE) -f CMakeFiles/appserver.dir/build.make CMakeFiles/appserver.dir/Server/AppServer.cpp.o
.PHONY : Server/AppServer.cpp.o

Server/AppServer.i: Server/AppServer.cpp.i

.PHONY : Server/AppServer.i

# target to preprocess a source file
Server/AppServer.cpp.i:
	$(MAKE) -f CMakeFiles/appserver.dir/build.make CMakeFiles/appserver.dir/Server/AppServer.cpp.i
.PHONY : Server/AppServer.cpp.i

Server/AppServer.s: Server/AppServer.cpp.s

.PHONY : Server/AppServer.s

# target to generate assembly for a file
Server/AppServer.cpp.s:
	$(MAKE) -f CMakeFiles/appserver.dir/build.make CMakeFiles/appserver.dir/Server/AppServer.cpp.s
.PHONY : Server/AppServer.cpp.s

TestClass/ReliableServer.o: TestClass/ReliableServer.cpp.o

.PHONY : TestClass/ReliableServer.o

# target to build an object file
TestClass/ReliableServer.cpp.o:
	$(MAKE) -f CMakeFiles/reliableserver.dir/build.make CMakeFiles/reliableserver.dir/TestClass/ReliableServer.cpp.o
.PHONY : TestClass/ReliableServer.cpp.o

TestClass/ReliableServer.i: TestClass/ReliableServer.cpp.i

.PHONY : TestClass/ReliableServer.i

# target to preprocess a source file
TestClass/ReliableServer.cpp.i:
	$(MAKE) -f CMakeFiles/reliableserver.dir/build.make CMakeFiles/reliableserver.dir/TestClass/ReliableServer.cpp.i
.PHONY : TestClass/ReliableServer.cpp.i

TestClass/ReliableServer.s: TestClass/ReliableServer.cpp.s

.PHONY : TestClass/ReliableServer.s

# target to generate assembly for a file
TestClass/ReliableServer.cpp.s:
	$(MAKE) -f CMakeFiles/reliableserver.dir/build.make CMakeFiles/reliableserver.dir/TestClass/ReliableServer.cpp.s
.PHONY : TestClass/ReliableServer.cpp.s

TestClass/ReliableTelnet.o: TestClass/ReliableTelnet.cpp.o

.PHONY : TestClass/ReliableTelnet.o

# target to build an object file
TestClass/ReliableTelnet.cpp.o:
	$(MAKE) -f CMakeFiles/reliabletelnet.dir/build.make CMakeFiles/reliabletelnet.dir/TestClass/ReliableTelnet.cpp.o
.PHONY : TestClass/ReliableTelnet.cpp.o

TestClass/ReliableTelnet.i: TestClass/ReliableTelnet.cpp.i

.PHONY : TestClass/ReliableTelnet.i

# target to preprocess a source file
TestClass/ReliableTelnet.cpp.i:
	$(MAKE) -f CMakeFiles/reliabletelnet.dir/build.make CMakeFiles/reliabletelnet.dir/TestClass/ReliableTelnet.cpp.i
.PHONY : TestClass/ReliableTelnet.cpp.i

TestClass/ReliableTelnet.s: TestClass/ReliableTelnet.cpp.s

.PHONY : TestClass/ReliableTelnet.s

# target to generate assembly for a file
TestClass/ReliableTelnet.cpp.s:
	$(MAKE) -f CMakeFiles/reliabletelnet.dir/build.make CMakeFiles/reliabletelnet.dir/TestClass/ReliableTelnet.cpp.s
.PHONY : TestClass/ReliableTelnet.cpp.s

TestClass/SecureServer.o: TestClass/SecureServer.cpp.o

.PHONY : TestClass/SecureServer.o

# target to build an object file
TestClass/SecureServer.cpp.o:
	$(MAKE) -f CMakeFiles/secureserver.dir/build.make CMakeFiles/secureserver.dir/TestClass/SecureServer.cpp.o
.PHONY : TestClass/SecureServer.cpp.o

TestClass/SecureServer.i: TestClass/SecureServer.cpp.i

.PHONY : TestClass/SecureServer.i

# target to preprocess a source file
TestClass/SecureServer.cpp.i:
	$(MAKE) -f CMakeFiles/secureserver.dir/build.make CMakeFiles/secureserver.dir/TestClass/SecureServer.cpp.i
.PHONY : TestClass/SecureServer.cpp.i

TestClass/SecureServer.s: TestClass/SecureServer.cpp.s

.PHONY : TestClass/SecureServer.s

# target to generate assembly for a file
TestClass/SecureServer.cpp.s:
	$(MAKE) -f CMakeFiles/secureserver.dir/build.make CMakeFiles/secureserver.dir/TestClass/SecureServer.cpp.s
.PHONY : TestClass/SecureServer.cpp.s

TestClass/SecureTelnet.o: TestClass/SecureTelnet.cpp.o

.PHONY : TestClass/SecureTelnet.o

# target to build an object file
TestClass/SecureTelnet.cpp.o:
	$(MAKE) -f CMakeFiles/securetelnet.dir/build.make CMakeFiles/securetelnet.dir/TestClass/SecureTelnet.cpp.o
.PHONY : TestClass/SecureTelnet.cpp.o

TestClass/SecureTelnet.i: TestClass/SecureTelnet.cpp.i

.PHONY : TestClass/SecureTelnet.i

# target to preprocess a source file
TestClass/SecureTelnet.cpp.i:
	$(MAKE) -f CMakeFiles/securetelnet.dir/build.make CMakeFiles/securetelnet.dir/TestClass/SecureTelnet.cpp.i
.PHONY : TestClass/SecureTelnet.cpp.i

TestClass/SecureTelnet.s: TestClass/SecureTelnet.cpp.s

.PHONY : TestClass/SecureTelnet.s

# target to generate assembly for a file
TestClass/SecureTelnet.cpp.s:
	$(MAKE) -f CMakeFiles/securetelnet.dir/build.make CMakeFiles/securetelnet.dir/TestClass/SecureTelnet.cpp.s
.PHONY : TestClass/SecureTelnet.cpp.s

TestClass/UdpServer.o: TestClass/UdpServer.cpp.o

.PHONY : TestClass/UdpServer.o

# target to build an object file
TestClass/UdpServer.cpp.o:
	$(MAKE) -f CMakeFiles/udpserver.dir/build.make CMakeFiles/udpserver.dir/TestClass/UdpServer.cpp.o
.PHONY : TestClass/UdpServer.cpp.o

TestClass/UdpServer.i: TestClass/UdpServer.cpp.i

.PHONY : TestClass/UdpServer.i

# target to preprocess a source file
TestClass/UdpServer.cpp.i:
	$(MAKE) -f CMakeFiles/udpserver.dir/build.make CMakeFiles/udpserver.dir/TestClass/UdpServer.cpp.i
.PHONY : TestClass/UdpServer.cpp.i

TestClass/UdpServer.s: TestClass/UdpServer.cpp.s

.PHONY : TestClass/UdpServer.s

# target to generate assembly for a file
TestClass/UdpServer.cpp.s:
	$(MAKE) -f CMakeFiles/udpserver.dir/build.make CMakeFiles/udpserver.dir/TestClass/UdpServer.cpp.s
.PHONY : TestClass/UdpServer.cpp.s

TestClass/UdpTelnet.o: TestClass/UdpTelnet.cpp.o

.PHONY : TestClass/UdpTelnet.o

# target to build an object file
TestClass/UdpTelnet.cpp.o:
	$(MAKE) -f CMakeFiles/udptelnet.dir/build.make CMakeFiles/udptelnet.dir/TestClass/UdpTelnet.cpp.o
.PHONY : TestClass/UdpTelnet.cpp.o

TestClass/UdpTelnet.i: TestClass/UdpTelnet.cpp.i

.PHONY : TestClass/UdpTelnet.i

# target to preprocess a source file
TestClass/UdpTelnet.cpp.i:
	$(MAKE) -f CMakeFiles/udptelnet.dir/build.make CMakeFiles/udptelnet.dir/TestClass/UdpTelnet.cpp.i
.PHONY : TestClass/UdpTelnet.cpp.i

TestClass/UdpTelnet.s: TestClass/UdpTelnet.cpp.s

.PHONY : TestClass/UdpTelnet.s

# target to generate assembly for a file
TestClass/UdpTelnet.cpp.s:
	$(MAKE) -f CMakeFiles/udptelnet.dir/build.make CMakeFiles/udptelnet.dir/TestClass/UdpTelnet.cpp.s
.PHONY : TestClass/UdpTelnet.cpp.s

UdpSocket.o: UdpSocket.cpp.o

.PHONY : UdpSocket.o

# target to build an object file
UdpSocket.cpp.o:
	$(MAKE) -f CMakeFiles/appclient.dir/build.make CMakeFiles/appclient.dir/UdpSocket.cpp.o
	$(MAKE) -f CMakeFiles/reliableserver.dir/build.make CMakeFiles/reliableserver.dir/UdpSocket.cpp.o
	$(MAKE) -f CMakeFiles/udptelnet.dir/build.make CMakeFiles/udptelnet.dir/UdpSocket.cpp.o
	$(MAKE) -f CMakeFiles/udpserver.dir/build.make CMakeFiles/udpserver.dir/UdpSocket.cpp.o
	$(MAKE) -f CMakeFiles/reliabletelnet.dir/build.make CMakeFiles/reliabletelnet.dir/UdpSocket.cpp.o
	$(MAKE) -f CMakeFiles/appserver.dir/build.make CMakeFiles/appserver.dir/UdpSocket.cpp.o
	$(MAKE) -f CMakeFiles/secureserver.dir/build.make CMakeFiles/secureserver.dir/UdpSocket.cpp.o
	$(MAKE) -f CMakeFiles/securetelnet.dir/build.make CMakeFiles/securetelnet.dir/UdpSocket.cpp.o
.PHONY : UdpSocket.cpp.o

UdpSocket.i: UdpSocket.cpp.i

.PHONY : UdpSocket.i

# target to preprocess a source file
UdpSocket.cpp.i:
	$(MAKE) -f CMakeFiles/appclient.dir/build.make CMakeFiles/appclient.dir/UdpSocket.cpp.i
	$(MAKE) -f CMakeFiles/reliableserver.dir/build.make CMakeFiles/reliableserver.dir/UdpSocket.cpp.i
	$(MAKE) -f CMakeFiles/udptelnet.dir/build.make CMakeFiles/udptelnet.dir/UdpSocket.cpp.i
	$(MAKE) -f CMakeFiles/udpserver.dir/build.make CMakeFiles/udpserver.dir/UdpSocket.cpp.i
	$(MAKE) -f CMakeFiles/reliabletelnet.dir/build.make CMakeFiles/reliabletelnet.dir/UdpSocket.cpp.i
	$(MAKE) -f CMakeFiles/appserver.dir/build.make CMakeFiles/appserver.dir/UdpSocket.cpp.i
	$(MAKE) -f CMakeFiles/secureserver.dir/build.make CMakeFiles/secureserver.dir/UdpSocket.cpp.i
	$(MAKE) -f CMakeFiles/securetelnet.dir/build.make CMakeFiles/securetelnet.dir/UdpSocket.cpp.i
.PHONY : UdpSocket.cpp.i

UdpSocket.s: UdpSocket.cpp.s

.PHONY : UdpSocket.s

# target to generate assembly for a file
UdpSocket.cpp.s:
	$(MAKE) -f CMakeFiles/appclient.dir/build.make CMakeFiles/appclient.dir/UdpSocket.cpp.s
	$(MAKE) -f CMakeFiles/reliableserver.dir/build.make CMakeFiles/reliableserver.dir/UdpSocket.cpp.s
	$(MAKE) -f CMakeFiles/udptelnet.dir/build.make CMakeFiles/udptelnet.dir/UdpSocket.cpp.s
	$(MAKE) -f CMakeFiles/udpserver.dir/build.make CMakeFiles/udpserver.dir/UdpSocket.cpp.s
	$(MAKE) -f CMakeFiles/reliabletelnet.dir/build.make CMakeFiles/reliabletelnet.dir/UdpSocket.cpp.s
	$(MAKE) -f CMakeFiles/appserver.dir/build.make CMakeFiles/appserver.dir/UdpSocket.cpp.s
	$(MAKE) -f CMakeFiles/secureserver.dir/build.make CMakeFiles/secureserver.dir/UdpSocket.cpp.s
	$(MAKE) -f CMakeFiles/securetelnet.dir/build.make CMakeFiles/securetelnet.dir/UdpSocket.cpp.s
.PHONY : UdpSocket.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... appclient"
	@echo "... edit_cache"
	@echo "... reliableserver"
	@echo "... udptelnet"
	@echo "... udpserver"
	@echo "... reliabletelnet"
	@echo "... appserver"
	@echo "... secureserver"
	@echo "... securetelnet"
	@echo "... AppSocket.o"
	@echo "... AppSocket.i"
	@echo "... AppSocket.s"
	@echo "... Client/AppClient.o"
	@echo "... Client/AppClient.i"
	@echo "... Client/AppClient.s"
	@echo "... ReliableSocket.o"
	@echo "... ReliableSocket.i"
	@echo "... ReliableSocket.s"
	@echo "... SecureSocket.o"
	@echo "... SecureSocket.i"
	@echo "... SecureSocket.s"
	@echo "... Server/AppServer.o"
	@echo "... Server/AppServer.i"
	@echo "... Server/AppServer.s"
	@echo "... TestClass/ReliableServer.o"
	@echo "... TestClass/ReliableServer.i"
	@echo "... TestClass/ReliableServer.s"
	@echo "... TestClass/ReliableTelnet.o"
	@echo "... TestClass/ReliableTelnet.i"
	@echo "... TestClass/ReliableTelnet.s"
	@echo "... TestClass/SecureServer.o"
	@echo "... TestClass/SecureServer.i"
	@echo "... TestClass/SecureServer.s"
	@echo "... TestClass/SecureTelnet.o"
	@echo "... TestClass/SecureTelnet.i"
	@echo "... TestClass/SecureTelnet.s"
	@echo "... TestClass/UdpServer.o"
	@echo "... TestClass/UdpServer.i"
	@echo "... TestClass/UdpServer.s"
	@echo "... TestClass/UdpTelnet.o"
	@echo "... TestClass/UdpTelnet.i"
	@echo "... TestClass/UdpTelnet.s"
	@echo "... UdpSocket.o"
	@echo "... UdpSocket.i"
	@echo "... UdpSocket.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

